"""empty message

Revision ID: 22e4c4692261
Revises: ea00807cd9ec
Create Date: 2021-09-09 23:29:35.089141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e4c4692261'
down_revision = 'ea00807cd9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_see')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_see', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
