"""remove language column

Revision ID: e8d9c90fa258
Revises: e64a5b9ad982
Create Date: 2021-09-12 15:41:07.317461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8d9c90fa258'
down_revision = 'e64a5b9ad982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language', sa.VARCHAR(length=3), nullable=True))
    # ### end Alembic commands ###
